#Project Euler - Problem 2 (from https://projecteuler.net/)
#Even Fibonacci numbers
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.
 
 
x = 1
y = 0
z = 0
a = 4000000
bool = true
answer = 0
loop do
   z = (x + y);
   x = z;
   y = z - y;
   if(z%2 == 0)
     answer+=z
   end
    
   if(z > a)
     bool = false
   end
   
   break if bool == false
end
puts answer
